### ISSUE TITLE
Cannot end turn soft lock

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#723] opened 2024-05-15 01:40 UTC
Symosol — Yesterday at 10:20 PM
Hi, would anyone be able to tell me why the game keeps randomly stopping mid match
LIke we end our turn and it doesn't switch to the enemies turn
Jordan - Spellmasons Creator — Today at 7:21 AM
Can you describe more about the state of the game when this happens?
How many players are you playing with?
Hotseat multiplayer or online?
All players have ended their turn? Are there any dead players?
Have you tried re-ending your turn more than once?
Are there any ally npcs in the game?
Does saving the game and loading it resolve the issue?

Like Soul said, our apologies for this issue! We will resolve it as soon as possible! 
Symosol — Today at 11:55 AM
No worries, its amazing you guys respond so intently. The only thing we've noticed (my wife and I play together) is that it occurred 3/4 times after using the freeze/push spell combo on the blue slime enemy. I can't remember the name. Could be coincidence but that's all we got. We're going to keep playing anyway because we love it xD and we'll update with anything new if its important. Thanks for making an awesome game.
I'll go by the bullet points.
2 Players
Multiplayer on the shark U.S. East server. All players have ended their turn. No-one has died. We have tried re-ending the turn and clicking on enemies as well as pressing escape. We didn't even know about summons, so none of those. And yes re-loading the game seems to help but, 1/2 times it will re-freeze on the next level.
I've played around 5 games alone and so far i haven't experienced a freeze if that helps at all.
chrillo — Today at 12:02 PM
Could it be because the enemies were out of mana to attack and thus instantly ended their turn to recharge mana? 
Or does the game completely freeze?
Symosol — Today at 12:04 PM
I had wondered about that but, it's more like our turn never ends. We can still move if we have stamina, can still cast spells if we have mana. But it's like the turn never actually cycles off ours, so the enemy turn won't continue,
---

@SoulMuncher I bet this has something to do with freeze if I had to guess

**Comment by SoulMuncher** [comment] 2024-05-15 01:42
duplicate of #683

**Closed by SoulMuncher** 2024-05-15 01:42 UTC
Labels: -Bug, -High Priority
