### ISSUE TITLE
Pull broken in 1.27 

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#330] opened 2024-01-03 23:03 UTC
> RainbowLuck — Today at 5:59 PM
> Ive try to pull someone with 7 pull he moved like 2 cm on the screen x) that was a normal golem

**Comment by SoulMuncher** [comment] 2024-01-04 05:01
Sorta made a duplicate of this.
Closing this one. Related #332

**Closed by SoulMuncher** 2024-01-04 05:01 UTC
Labels: -Bug
