### ISSUE TITLE
Blue portals invisible

### ISSUE THREAD

**Issue by SoulMuncher** [jdoleary/Spellmasons#84] opened 2023-12-09 18:21 UTC
Blue portals are sometimes invisible, but still selectable and usable.

Edit: This was in multiplayer. For me, one portal was visible and the other was not. For my teamate, both portals were visible.

**Comment by jdoleary** [comment] 2023-12-09 21:14
I thought I solved this.  Initially, I thought it was due to the Graphics option where you could limit particles.  To fix that, I made a sprite version of the blue and red portals that is used when the particles are limited.  If this is still happening in the current version, please investigate when it occurs or try to take note of reproduction steps because I have been unable to reproduce it.  
It might be a sync issue if this is occurring on multiplayer (only online multiplayer, hotseat counts as singleplayer and shouldn't encounter sync issues).

**Comment by SoulMuncher** [comment] 2023-12-09 21:24
@jdoleary  (updated first comment)

**Comment by jdoleary** [comment] 2023-12-10 01:52
Okay good to know, this is in fact a different problem than I thought it was then.  I wonder why just portals tho and not other pickups...
Oh and only blue portals might be a clue, since they're placed around the map during level creation.  I wonder if the same goes for the Deathmason's red portals

**Comment by SoulMuncher** [comment] 2023-12-21 04:18
Sometimes the portals appear more/less intense than normal. Like bigger, and darker/more saturated. Not sure if that's related, maybe there's a shader thing going on.

**Comment by jdoleary** [comment] 2023-12-21 13:12
Ooh interesting, there's no shader used on the portals, it's just particles.  If you can get me a screenshot of what you mean that'd be really helpful.  It may be the sprite backup of the particle portal if particles are turned to Low

**Comment by jdoleary** [comment] 2023-12-28 22:31
@SoulMuncher I'm going to remove this from 1.27 unless we can reproduce it.

**Comment by SoulMuncher** [comment] 2023-12-28 22:35
Sounds good. I haven't seen it again since making the issue

**Comment by jdoleary** [comment] 2024-01-12 22:48
Closing as old

**Closed by jdoleary** 2024-01-12 22:48 UTC
Labels: -Bug, .Visual only, .Needs Repro
