### ISSUE TITLE
Softlock on disconnect bug

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#692] opened 2024-05-02 10:19 UTC
verify that you're able to carry on the round even if one player disconnects from the server.

https://discord.com/channels/1032294536640200766/1235429654773628949/1235429654773628949

**Comment by SoulMuncher** [comment] 2024-05-02 19:10
Verified that you can continue playing even if one player disconnects from the server.
- P2 left, P1 was able to end turn, do next turn to finish level, progress to the next level, and end turn there.
- Also tested with P1 (host) leaving and found no issues.

I'm thinking the disconnect is unrelated, and this is a duplicate of #683

**Comment by SoulMuncher** [comment] 2024-05-02 19:16
Oops, I didn't realize this was referring to a hotseat game. Also, strange update from Jerm (bug reporter)

> We were playing on the same computer technically, but through Parsec. Not sure how that would make a difference. Let me know what I can help with. We are loving this game. All of us 1000s of hours in Noita already so this feels too familiar.

**Closed** 2024-05-09 17:53 UTC
Labels: .Invalid
