### ISSUE TITLE
Toxic urn visual lags behind effect sometimes

### ISSUE THREAD

**Issue by jdoleary** [jdoleary/Spellmasons#394] opened 2024-01-17 11:41 UTC
> Blue — Yesterday at 9:56 PM
> its seems like the visual sometimes doesnt work for the toxic urn but the ability goes off in multiplayer. honestly it might just be lag? it sometimes goes off like many turns after visually 
>

**Comment by SoulMuncher** [comment] 2024-01-21 00:10
Related? #399 

I was able to reproduce this by spamming a few arrows at some nearby units, and then spamming some arrows at the urns, and then spamming more arrows at other nearby units, as quickly as I could and without waiting for spell resolution.

The urns were deleted from my screen long before they were ever hit by arrows, as if killing the other units had caused a sync that deleted the urns. Maybe the urns were already destroyed on headless because headless simulated all of the force moves in advance, while the real game loop had to wait for each arrow promise one by one?

**Comment by SoulMuncher** [comment] 2024-01-28 00:52
Should be fixed with #402 and #410 ?

**Closed** 2024-04-22 05:55 UTC
Labels: .Visual only, .Needs Testing
